ls  bin/ATFWD-daemon
ls  bin/bridgemgrd
ls  bin/btnvtool
ls  bin/diag_klog
ls  bin/diag_mdlog
ls  bin/ds_fmc_appd
ls  vendor/firmware/discretix/dxhdcp2.b00
ls  vendor/firmware/discretix/dxhdcp2.b01
ls  vendor/firmware/discretix/dxhdcp2.b02
ls  vendor/firmware/discretix/dxhdcp2.b03
ls  vendor/firmware/discretix/dxhdcp2.mdt
ls  bin/efsks
ls  bin/hci_qcomm_init
ls  bin/mm-qcamera-deamon
ls  vendor/firmware/keymaster/keymaster.b00
ls  vendor/firmware/keymaster/keymaster.b01
ls  vendor/firmware/keymaster/keymaster.b02
ls  vendor/firmware/keymaster/keymaster.b03
ls  vendor/firmware/keymaster/keymaster.mdt
ls  vendor/firmware/q6.b00
ls  vendor/firmware/q6.b01
ls  vendor/firmware/q6.b03
ls  vendor/firmware/q6.b04
ls  vendor/firmware/q6.b05
ls  vendor/firmware/q6.b06
ls  vendor/firmware/q6.mdt
ls  vendor/firmware/wcnss.b00
ls  vendor/firmware/wcnss.b01
ls  vendor/firmware/wcnss.b02
ls  vendor/firmware/wcnss.b04
ls  vendor/firmware/wcnss.b05
ls  vendor/firmware/wcnss.mdt
ls  bin/ks
ls  vendor/lib/egl/libEGL_adreno.so
ls  vendor/lib/egl/libGLESv1_CM_adreno.so
ls  vendor/lib/egl/libGLESv2_adreno.so
ls  vendor/lib/egl/libplayback_adreno.so
ls  vendor/lib/egl/libq3dtools_adreno.so
ls  lib/libAKM.so
ls  vendor/lib/libCB.so
ls  lib/libCommandSvc.so
ls  lib/libI420colorconvert.so
ls  lib/libQSEEComAPI.so
ls  lib/libacdbdata.so
ls  lib/libacdbloader.so
ls  vendor/lib/libadreno_utils.so
ls  lib/libaudcal.so
ls  lib/libaudioalsa.so
ls  lib/libcamera_fast_af.so
ls  vendor/lib/libc2d30-a3xx.so
ls  vendor/lib/libc2d30.so
ls  lib/libchromatix_imx111_default_video.so
ls  lib/libchromatix_imx111_preview.so
ls  lib/libchromatix_imx111_vt.so
ls  lib/libchromatix_imx111_zsl.so
ls  lib/libchromatix_imx091_default_video.so
ls  lib/libchromatix_imx091_preview.so
ls  lib/libchromatix_imx091_video_hd.so
ls  lib/libchromatix_imx091_zsl.so
ls  lib/libchromatix_mt9e013_default_video.so
ls  lib/libchromatix_mt9e013_preview.so
ls  lib/libchromatix_mt9e013_video_hfr.so
ls  lib/libchromatix_ov5647_default_video.so
ls  lib/libchromatix_ov5647_preview.so
ls  lib/libchromatix_ov5647_video_hfr.so
ls  lib/libchromatix_ov8825_default_video.so
ls  lib/libchromatix_ov8825_preview.so
ls  lib/libchromatix_ov9726_default_video.so
ls  lib/libchromatix_ov9726_preview.so
ls  lib/libchromatix_s5k4e1_default_video.so
ls  lib/libchromatix_s5k4e1_preview.so
ls  lib/libchromatix_vx6953_default_video.so
ls  lib/libchromatix_vx6953_preview.so
ls  lib/libconfigdb.so
ls  lib/libcsd-client.so
ls  lib/libdiag.so
ls  vendor/lib/libdrmdecrypt.so
ls  vendor/lib/libgeofence.so
ls  vendor/lib/libizat_core.so
ls  vendor/lib/libloc_ds_api.so
ls  lib/libdrmdiag.so
ls  lib/libdrmfs.so
ls  lib/libdrmtime.so
ls  vendor/lib/librs_adreno_sha1.so
ls  vendor/lib/librs_adreno.so
ls  vendor/lib/libRSDriver_adreno.so
ls  lib/libdsi_netctrl.so
ls  lib/libdsprofile.so
ls  lib/libdss.so
ls  lib/libdsucsd.so
ls  lib/libdsutils.so
ls  lib/libgemini.so
ls  lib/libimage-jpeg-dec-omx-comp.so
ls  lib/libimage-jpeg-enc-omx-comp.so
ls  lib/libimage-omx-common.so
ls  lib/libloc_api_v02.so
ls  lib/libloc_core.so
ls  lib/libmm-color-convertor.so
ls  lib/libmmcamera_faceproc.so
ls  lib/libmmcamera_frameproc.so
ls  lib/libmmcamera_statsproc31.so
ls  lib/libmmipl.so
ls  lib/libmmjpeg.so
ls  lib/libmmjps.so
ls  lib/libmmmpo.so
ls  lib/libmmmpod.so
ls  lib/libmmstillomx.so
ls  lib/libmorpho_noise_reduction.so
ls  lib/libnetmgr.so
ls  lib/liboemcamera.so
ls  lib/liboemcrypto.so
ls  lib/libqcci_legacy.so
ls  lib/libqdi.so
ls  lib/libqdp.so
ls  lib/libqmi.so
ls  lib/libqmi_cci.so
ls  lib/libqmi_client_qmux.so
ls  lib/libqmi_common_so.so
ls  lib/libqmi_csi.so
ls  lib/libqmi_csvt_srvc.so
ls  lib/libqmi_encdec.so
ls  lib/libqmiservices.so
ls  lib/libril-qc-qmi-1.so
ls  lib/libril-qcril-hook-oem.so
ls  lib/libsensor1.so
ls  lib/libsensor_user_cal.so
ls  lib/libstagefright_hdcp.so
ls  bin/mm-qcamera-daemon
ls  bin/mpdecision
ls  bin/netmgrd
ls  bin/nl_listener
ls  bin/port-bridge
ls  bin/qcks
ls  bin/qmuxd
ls  bin/qseecomd
ls  bin/radish
ls  bin/rmt_storage
ls  lib/hw/flp.msm8960.so
ls  lib/hw/sensors.msm8960.so
ls  bin/sensors.qcom
ls  bin/thermald
ls  etc/firmware/tzapps.b00
ls  etc/firmware/tzapps.b01
ls  etc/firmware/tzapps.b02
ls  etc/firmware/tzapps.b03
ls  etc/firmware/tzapps.mdt
ls  bin/usbhub
ls  bin/usbhub_init
ls  bin/v4l2-qcamera-app
ls  etc/firmware/vidc.mdt
ls  etc/firmware/vidc.b00
ls  etc/firmware/vidc.b01
ls  etc/firmware/vidc.b02
ls  etc/firmware/vidc.b03
ls  etc/firmware/vidc_1080p.fw
ls  vendor/firmware/a300_pfp.fw
ls  vendor/firmware/a300_pm4.fw
ls  vendor/lib/libC2D2.so
ls  vendor/lib/libgsl.so
ls  vendor/lib/libllvm-qcom.so
ls  vendor/lib/libbccQTI.so
ls  vendor/lib/libsc-a3xx.so
ls  lib/libidl.so
ls  lib/libmercury.so
ls  lib/libmmcamera_hdr_lib.so
ls  lib/libmmcamera_image_stab.so
ls  lib/libmmcamera_wavelet_lib.so
ls  lib/libsensor_reg.so
ls  lib/libxml.so
